WritersCorner/Controllers/CharacterController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WritersCorner.Data.Entities.EntitiesBook;
using WritersCorner.Mappers.CharacterM;
using WritersCorner.Models.CharacterVM;
using WritersCorner.Service.Contracts;
using WritersCorner.Service.CustomException;
using WritersCorner.Service.Providers;

namespace WritersCorner.Controllers
{
    public class CharacterController : Controller
    {
        private readonly ICharacterServices _characterServices;
        private readonly IFileService _fileService;

        public CharacterController(ICharacterServices characterServices, IFileService fileService)
        {
            this._characterServices = characterServices;
            this._fileService = fileService;
        }

        public async Task<IActionResult> Index(int? currentPage, string search = null)
        {
            try
            {
                string userId = FindCurrentUserId();

                int currPage = currentPage ?? 1;
                int totalPages = await _characterServices.GetPageCount();

                IEnumerable<Character> characterAllResults = null;

                if (!string.IsNullOrEmpty(search))
                {
                    //For character search
                    characterAllResults = await _characterServices.SearchCharacter(search, currPage, userId);
                }
                else
                {
                    characterAllResults = await _characterServices.GetAllUserCharactersAsync(currPage, userId);
                }

                IEnumerable<CharacterViewModel> characterListing = characterAllResults
                    .Select(m => CharacterMapper.MapCharacter(m));
                CharacterIndexViewModel characterIVM = CharacterMapper.MapFromCharacterIndex(characterListing,
                    currPage, totalPages);

                #region For pagination buttons and distribution
                characterIVM.CurrentPage = currPage;
                characterIVM.TotalPages = totalPages;

                if (totalPages > currPage)
                {
                    characterIVM.NextPage = currPage + 1;
                }

                if (currPage > 1)
                {
                    characterIVM.PreviousPage = currPage - 1;
                }
                #endregion

                return View(characterIVM);
            }
            catch (GlobalException e)
            {
                //TODO
                return BadRequest(e.Message);
                //ModelState.AddModelError(string.Empty, ExceptionMessage.GlobalErrorMessage);
                //return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> Detail(int Id)
        {
            try
            {
                Character character = await _characterServices.GetCharacterAsync(Id);
                CharacterViewModel userModel = CharacterMapper.MapCharacter(character);

                return View("Detail", userModel);
            }
            catch (GlobalException e)
            {
                //TODO
                return BadRequest(e.Message);
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CharacterViewModel viewModel)
        {
            try
            {
                SaveFile(viewModel);

                string userId = FindCurrentUserId();

                Character mapCharacter = CharacterMapper.MapCharacter(viewModel);
                Character character = await _characterServices.CreateCharacterAsync(mapCharacter, userId);

                return RedirectToAction("Index", new { id = character.Id });
            }
            catch (GlobalException e)
            {
                //return BadRequest(e.Message);
                return NotFound();
            }
        }

        //За пълнене на формата със стойности
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Id)
        {
            Character character = await _characterServices.GetCharacterAsync(Id);
            CharacterViewModel mapCharacter = CharacterMapper.MapCharacter(character);

            return View("Edit", mapCharacter);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCharacter(CharacterViewModel viewModel)
        {
            try
            {
                Character mapCharacterToCharacter = CharacterMapper.MapCharacter(viewModel);
                Character character = await _characterServices.EditCharacterAsync(mapCharacterToCharacter);
                CharacterViewModel mapCharacter = CharacterMapper.MapCharacter(character);

                return View("Detail", mapCharacter);
            }
            catch (GlobalException e)
            {
                //TODO
                return BadRequest(e.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCharacter(int Id)
        {
            try
            {
                //TODO: Да направя confirm прозорец при триене
                string userId = FindCurrentUserId();
                await _characterServices.DeleteCharacterAsync(Id, userId);

                return RedirectToAction("Index");
            }
            catch (GlobalException e)
            {
                //return NotFound();
                return BadRequest(e.Message);
            }
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UserCharacters(int? currentPage, string search = null)
        {
            try
            {
                string userId = FindCurrentUserId();

                int currPage = currentPage ?? 1;
                int totalPages = await _characterServices.GetPageCount();

                IEnumerable<Character> characterAllResults = null;

                if (!string.IsNullOrEmpty(search))
                {
                    //For character search
                    characterAllResults = await _characterServices.SearchCharacter(search, currPage, userId);
                }
                else
                {
                    characterAllResults = await _characterServices.GetAllUserCharactersAsync(currPage, userId);
                }

                IEnumerable<CharacterViewModel> characterListing = characterAllResults
                    .Select(m => CharacterMapper.MapCharacter(m));
                CharacterIndexViewModel characterIVM = CharacterMapper.MapFromCharacterIndex(characterListing,
                    currPage, totalPages);

                #region For pagination buttons and distribution
                characterIVM.CurrentPage = currPage;
                characterIVM.TotalPages = totalPages;

                if (totalPages > currPage)
                {
                    characterIVM.NextPage = currPage + 1;
                }

                if (currPage > 1)
                {
                    characterIVM.PreviousPage = currPage - 1;
                }
                #endregion

                return View(characterIVM);
            }
            catch (GlobalException e)
            {
                //TODO
                return BadRequest(e.Message);
            }
        }

        public string FindCurrentUserId()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            return userId;
        }

        public void SaveFile(CharacterViewModel viewModel)
        {
            if (viewModel.ImagePath != null)
            {
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Pictures\\Images\\CharacterImages");
                _fileService.CreateFolder(uploadsFolder);

                string imageName = Path.GetFileName(viewModel.File.FileName);
                string fullFilePath = Path.Combine(uploadsFolder, imageName);

                viewModel.ImagePath = imageName;

                using (FileStream stream = new FileStream(fullFilePath, FileMode.Create))
                {
                    using (MemoryStream memoryStream = new MemoryStream())
                    {
                        viewModel.File.CopyToAsync(memoryStream);
                        byte[] x = memoryStream.ToArray();
                        stream.Write(x, 0, x.Length);
                    }
                }
            }
            else
            {
                viewModel.ImagePath = "default.png";
            }
        }
    }
}

WritersCorner/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WritersCorner.Data.Entities;
using WritersCorner.Mappers;
using WritersCorner.Models.UserVM;
using WritersCorner.Service.Contracts;
using WritersCorner.Service.CustomException;

namespace WritersCorner.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserServices _userService;

        public UserController(IUserServices userService)
        {
            this._userService = userService;
        }

        public async Task<IActionResult> Index(int? currentPage, string search = null)
        {
            int currentP = currentPage ?? 1;
            int totalPages = await _userService.GetPageCountAsync();

            IEnumerable<User> allUsers = null;

            if (!string.IsNullOrEmpty(search))
            {
                allUsers = await _userService.SearchUserAsync(search, currentP);
            }
            else
            {
                allUsers = await _userService.GetAllUsersAsync(currentP);
            }

            var userListing = allUsers
                .Select(u => UserMapper.MapUser(u));
            var userModel = UserMapper.MapUserIndex(userListing, currentP, totalPages);

            userModel.CurrentPage = currentP;
            userModel.TotalPages = totalPages;

            if (totalPages > currentP)
            {
                userModel.NextPage = currentP + 1;
            }
            if (currentP > 1)
            {
                userModel.PreviousPage = currentP - 1;
            }

            return View(userModel);
        }

        public async Task<IActionResult> Detail(string userId)
        {
            User user = await _userService.GetUserAsync(userId);
            UserViewModel userModel = UserMapper.MapUser(user);

            return View("Detail", userModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> BanUser(string userId, int banDays, string banReason)
        {
            try
            {
                //TODO - to find how to clear the text in the ban form
                string bannedFrom = User.FindFirstValue(ClaimTypes.NameIdentifier);
                User user = await _userService.BanUserAsync(userId, banDays, banReason, bannedFrom);

                var userModel = UserMapper.MapUser(user);

                return View("Detail", userModel);
            }
            catch (GlobalException e)
            {
                //TODO - pop-up message - not new page?
                return BadRequest(e.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> RemoveBan(string userId)
        {
            try
            {
                User user = await _userService.RemoveBanAsync(userId);
                var userModel = UserMapper.MapUser(user);

                return View("Detail", userModel);
            }
            catch (GlobalException e)
            {
                //TODO
                return BadRequest(e.Message);
            }
        }
    }
}

WritersCorner/Views/Shared/_BanUserPartialView.cshtml
@model UserViewModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<button type="button" class="btn btn-primary btn-block btn-lg" data-toggle="modal" data-target="#exampleModal">
    Ban
</button>

<div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ban @Model.Username</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form enctype="multipart/form-data" asp-controller="User" asp-action="BanUser" asp-route-userId="@Model.Id">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="BanDays" class="control-label">Ban for days:</label>
                        <input asp-for="BanDays" class="form-control" />
                        <span asp-validation-for="BanDays" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BanReason" class="control-label">Ban reason:</label>
                        <input asp-for="BanReason" class="form-control" />
                        <span asp-validation-for="BanReason" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

WritersCorner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WritersCorner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <!---->
    @*<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">*@
    @*<link rel="stylesheet" href="~/css/templatemo-style.css">*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WritersCorner</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Character" asp-action="Index">Character list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Character" asp-action="Create">Create-character</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="row">
            <div class="col-lg-12">
                <p class="text-center small tm-copyright-text mb-0">
                    Copyright &copy; <span class="tm-current-year">2020</span>
                    Writers Corner
                </p>
                <script>

                    /* DOM is ready */
                    $(function () {

                        if (renderPage) {
                            $('body').addClass('loaded');
                        }

                        $('.tm-current-year').text(new Date().getFullYear());  // Update year in copyright
                    });

                </script>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>